;
; File generated by cc65 v 2.19 - Git cc3c40c
;
	.fopt		compiler,"cc65 v 2.19 - Git cc3c40c"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_set_irq
	.export		_initIrq
	.import		_irq
	.import		_frameCount
	.import		_tempStack

; ---------------------------------------------------------------
; void __near__ initIrq (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initIrq: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     _frameCount
	sei
	ldx     #$00
	lda     #$00
	sta     $D012
	ldx     #$00
	lda     $D01A
	ora     #$01
	ldx     #$00
	sta     $D01A
	lda     #<(_irq)
	ldx     #>(_irq)
	jsr     pushax
	lda     #<(_tempStack)
	ldx     #>(_tempStack)
	jsr     pushax
	ldx     #$00
	lda     #$40
	jsr     _set_irq
	cli
	rts

.endproc

