; ---------------------------------------------------------------
; list of generic definitions for the project
; ---------------------------------------------------------------

; *** directions ***
NORTH			:= 0
EAST			:= 1
SOUTH			:= 2
WEST			:= 3

UP              := 1
DOWN            := 2
LEFT            := 4
RIGHT           := 8

; *** screen things ***
FPS				:= 50
X_OFFSET        := 24
Y_OFFSET        := 50

; *** colors ***
BLACK			:= $00
WHITE			:= $01
RED				:= $02
CYAN			:= $03
VIOLET			:= $04
GREEN			:= $05
BLUE			:= $06
YELLOW			:= $07
ORANGE			:= $08
BROWN			:= $09
LIGHT_RED		:= $0A
DARK_GREY		:= $0B
MED_GREY		:= $0C
LIGHT_GREEN		:= $0D
LIGHT_BLUE		:= $0E
LIGHT_GREY		:= $0F

; *** disk operation stuff ***
LFN				:= $02
COMMAND			:= $0F
FLOPPY			:= $08
MANIFEST_AREA	:= $9000
VICII_BANK_AREA	:= $C000
